---
version: 0.2

phases:
  install:
    commands:
      - |
        cd ../
        yum install -y unzip
        readonly TERRAFORM_VERSION=$(cat bichard7-next-shared-infrastructure/.terraform-version | xargs)
        readonly TF_URL="https://releases.hashicorp.com/terraform"
        readonly TF_ZIP="terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
        wget ${TF_URL}/${TERRAFORM_VERSION}/${TF_ZIP}
        unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        chmod +x terraform
        mv terraform /usr/bin/.
        cd bichard7-next-shared-infrastructure
  build:
    commands:
      - set -e
      - |
        cd terraform/shared_account_${ENVIRONMENT}_infra_ci
        TF_VAR_is_cd=true terraform init
        TF_VAR_is_cd=true terraform apply -auto-approve
