variable "sns_kms_key_arn" {
  description = "The kms key arn used to encrypt our sns queue"
  type        = string
}

variable "name" {
  description = "The name we have assigned our resource"
  type        = string
}

variable "event_type_ids" {
  description = "A list of event types we want to notify on"
  type        = list(string)
  default = [
    "codebuild-project-build-state-failed"
  ]
}

variable "notification_source_arn" {
  description = "The arn our notification is generated by"
  type        = string
}

variable "sns_notification_arn" {
  description = "The arn our notification will be posted to"
  type        = string
}

variable "ci_cd_service_role_name" {
  description = "The service role name that will be triggering the notification"
  type        = string
}

variable "tags" {
  description = "A map of resource tags"
  type        = map(string)
}
