name: IAM Access Key Audit

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  audit-keys:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        #TODO: add action that alerts if fails
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install boto3 slack-sdk

      - name: Run Audit Script
        shell: bash
        working-directory: ./scripts
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          python3 check_access_key_age.py
