name: IAM Access Key Audit

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  audit-access-keys:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'GitHub action failed'
          message_format: ':elmo-fire: *{workflow}* {status_message} in <{repo_url}|{repo}>'
          notify_when: 'failure'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install boto3 slack-sdk

      - name: Run Audit Script
        shell: bash
        working-directory: ./scripts
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          ACCESS_KEY_WARN_AGE_DAYS: 70
          ACCESS_KEY_EXPIRY_AGE_DAYS: 90
        run: |
          python3 check_access_key_age.py
