name: Format code

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          persist-credentials: 'false'

      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@8c77d3a65a46d1d4b5416eafae5b84371ecd797d # v1.5.0

      - uses: ministryofjustice/github-actions/code-formatter@db1a54895bf5fb975c60af47e5a3aab96505ca3e #v18.6.0
        with:
          ignore-files: ".python-version,*.py"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
